[package]
name = "hitome"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2"
fnv = "1.0.7"
argh = { version = "0.1.13", default-features = false, features = ["help"] }
nvml-wrapper = { version = "0.8.0", optional = true }

[features]
default = []
nvml = ["dep:nvml-wrapper"]

# see https://github.com/johnthagen/min-sized-rust
[profile.release]
strip = true
lto = true
codegen-units = 1
panic = "abort"
